services:
  builder:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:latest
        RUN apt-get update && apt-get install -y cloud-image-utils
    command: cloud-localds user-data.img cloud-config.yml
    volumes:
      - .:/work
    working_dir: /work